version: '3.8'
services:
  webdav:
    image: bytemark/webdav
    ports:
      - ${WEBDAV_PORT}:80
    volumes:
      - ./data/dav-data:/var/lib/dav
    environment:
      - AUTH_TYPE=Basic
      - USERNAME=${USER_NAME_WEBDAV}
      - PASSWORD=${PASSWORD_WEBDAV}
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    driver: bridge
    name: main